name: Auto Requirements Update
on: [push]
jobs: 
 update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Automatic requirements.txt for Python Projects
        uses: ryan-rozario/pipreqs-action@v3.0.0

